name: Setup Scarb
description: Sets up Scarb in your GitHub Actions workflow
author: Software Mansion
branding:
  color: blue
  icon: activity
inputs:
  scarb-version:
    description: Scarb version to use
    required: false
  tool-versions:
    description: Path to .tool-versions file
    required: false
  scarb-lock:
    description: Path to Scarb.lock file
    required: false
  cache:
    description: Enable dependency caching
    required: false
    default: "true"
  cache-targets:
    description: If caching is enabled, cache target directories as well
    required: false
    default: "true"
outputs:
  scarb-prefix:
    description: The prefix of the installed Scarb
  scarb-version:
    description: The version of the installed Scarb
runs:
  using: "node20"
  main: "dist/setup/index.js"
  post: "dist/cache-save/index.js"
  post-if: success()
