name: Setup Scarb
description: Sets up Scarb in your GitHub Actions workflow
author: Software Mansion
branding:
  color: blue
  icon: activity
inputs:
  scarb-version:
    description: Scarb version to use
    default: "latest"
outputs:
  scarb-prefix:
    description: The prefix of the installed Scarb
  scarb-version:
    description: The version of the installed Scarb
runs:
  using: "node16"
  main: "dist/index.js"
